export const IssueCodes = {
  CORE_NO_SPECIFIC_CONTRACT: 'CORE_NO_SPECIFIC_CONTRACT',
  CORE_STRICT_POLICY_VIOLATION: 'CORE_STRICT_POLICY_VIOLATION',
  DIFF_ROUNDTRIP_IMPORT_FAILED: 'DIFF_ROUNDTRIP_IMPORT_FAILED',
  DIFF_ELEMENT_DROPPED: 'DIFF_ELEMENT_DROPPED',
  DIFF_ELEMENT_MISSING_LOSSLESS: 'DIFF_ELEMENT_MISSING_LOSSLESS',
  DIFF_TIMING_MISMATCH_OVER_TOLERANCE: 'DIFF_TIMING_MISMATCH_OVER_TOLERANCE',
  DIFF_DURATION_MISMATCH_OVER_TOLERANCE: 'DIFF_DURATION_MISMATCH_OVER_TOLERANCE',
  DIFF_TEMPO_MISMATCH_OVER_TOLERANCE: 'DIFF_TEMPO_MISMATCH_OVER_TOLERANCE',
  DIFF_TIME_SIGNATURE_MISMATCH: 'DIFF_TIME_SIGNATURE_MISMATCH',
  DIFF_PITCH_MISMATCH: 'DIFF_PITCH_MISMATCH',
  DIFF_VELOCITY_MISMATCH_OVER_TOLERANCE: 'DIFF_VELOCITY_MISMATCH_OVER_TOLERANCE',
  DIFF_CONTROLLER_VALUE_MISMATCH: 'DIFF_CONTROLLER_VALUE_MISMATCH',
  DIFF_MARKER_MISMATCH: 'DIFF_MARKER_MISMATCH',
  DIFF_TRACK_MAPPING_CHANGED: 'DIFF_TRACK_MAPPING_CHANGED',
  DIFF_ADDED_ELEMENTS_IGNORED: 'DIFF_ADDED_ELEMENTS_IGNORED',
  DIFF_UNKNOWN_KIND_SKIPPED: 'DIFF_UNKNOWN_KIND_SKIPPED',
} as const;

export type IssueCode = (typeof IssueCodes)[keyof typeof IssueCodes];
